# ===========================
#  NOMBRE DE LA APLICACIÓN
# ===========================
spring.application.name=cruz_ozzy

# ===========================
#  CONFIGURACIÓN DE BASE DE DATOS
# ===========================
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sabormasterclass?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&disabledAuthenticationPlugins=auth_gssapi_client
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===========================
#  CONFIGURACIÓN DE CORREO (SMTP)
# ===========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sabormasterclass@gmail.com
spring.mail.password=rvlc cqoi mbxp muzy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true